#include "stm32f4xx.h"
unsigned int blue=5,green=5,red=5;
void TIM3_IRQHandler(){
	TIM3->SR &= ~TIM_SR_UIF;
	if(blue>95)
	{
		blue=5;
		green+=1;
		if(GPIOD->ODR & GPIO_ODR_OD13){
		TIM3->CCR2 &= ~TIM_PSC_PSC;
		TIM3->CCR2 |= green;				
		GPIOD->ODR &= ~GPIO_ODR_OD13;
		}
		else{
		GPIOD->ODR |= GPIO_ODR_OD13;
		TIM3->CCR2 &= ~TIM_PSC_PSC;
		TIM3->CCR2 |= green;	
		}
		if(green>95)
		{
			green=5;
			red+=1;
			if(GPIOD->ODR & GPIO_ODR_OD14){
			TIM3->CCR3 &= ~TIM_PSC_PSC;
			TIM3->CCR3 |= red;					
			GPIOD->ODR &= ~GPIO_ODR_OD14;
			}
			else{
			GPIOD->ODR |= GPIO_ODR_OD14;
			TIM3->CCR3 &= ~TIM_PSC_PSC;
			TIM3->CCR3 |= red;	
			}
			if(red>95)
			{
			red=5;
			}
		}	
	}
	
	if(GPIOD->ODR & GPIO_ODR_OD12){	
		blue+=100;
		TIM3->CCR1 &= ~TIM_PSC_PSC;
		TIM3->CCR1 |= blue;	
		GPIOD->ODR &= ~GPIO_ODR_OD12;
	}
	else{
		TIM3->CCR1 &= ~TIM_PSC_PSC;
		TIM3->CCR1 |= blue;	
		GPIOD->ODR |= GPIO_ODR_OD12;
	}

}
int main(){
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN|RCC_AHB1ENR_GPIOBEN|RCC_AHB1ENR_GPIOCEN|RCC_AHB1ENR_GPIODEN; 
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	
	GPIOA->MODER |= GPIO_MODER_MODER6_1; //TIM3 3CH IÇIN PA6,PA7 VE PB0 PORTLARI AKTIF EDILMELIDIR.
	GPIOB->MODER |= GPIO_MODER_MODER5_1;
	GPIOC->MODER |= GPIO_MODER_MODER8_1;
	GPIOD->MODER |= GPIO_MODER_MODER14_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER12_0;
	
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL6_1;//TIM 3 IÇIN ALTERNATIF FONKSIYONLAR AKTIF EDILIR.
	GPIOB->AFR[0] |= GPIO_AFRL_AFRL5_1;
	GPIOC->AFR[1] |= GPIO_AFRH_AFRH0_1;
	
	
		
	TIM3->PSC &= ~TIM_PSC_PSC;//16MGHZ 1 MGHZ E DÜSÜRÜLÜR.
	TIM3->PSC |= 15U;
	
	TIM3->ARR &= ~TIM_PSC_PSC;
	TIM3->ARR |= 1000U;
	
	TIM3->CCR1 &= ~TIM_PSC_PSC;
	TIM3->CCR1 |= blue;
	TIM3->CCR2 &= ~TIM_PSC_PSC;
	TIM3->CCR2 |= green;
	TIM3->CCR3 &= ~TIM_PSC_PSC;
	TIM3->CCR3 |= red;
	
	TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1;//PWM MODE 1 SEÇILIR.
	TIM3->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1;
	TIM3->CCMR2 |= TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 ;
	
	//TIM3->CCER |= TIM_CCER_CC1P | TIM_CCER_CC2P | TIM_CCER_CC3P;
	TIM3->CCER |= TIM_CCER_CC1E| TIM_CCER_CC2E | TIM_CCER_CC3E;//CAPTURE/COMPARE AKTIF EDILIR.
	
	TIM3->DIER |= TIM_DIER_UIE;//UPDATE INTERRUPT SEÇILIR.
	
	NVIC_EnableIRQ(TIM3_IRQn);//TIM 3 NVICTEN AKTIF EDILIR.
	
	TIM3->CR1 |= TIM_CR1_CEN;//TIM3 3CH BASLATILIRÇ.
	
	GPIOD->ODR |= GPIO_ODR_OD12;
	GPIOD->ODR |= GPIO_ODR_OD13;
	GPIOD->ODR |= GPIO_ODR_OD14;
	while(1);
}
